config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/jobs/new', to: 'jobs#new'
  post '/jobs', to: 'jobs#create'
  
  get '/jobs', to: "jobs#index"
  get "/jobs/:id", to: "jobs#show", as: "job"
  get '/jobs/:id/edit', to: 'jobs#edit', as: 'edit_job'
  patch '/jobs/:id',to: 'jobs#update'
  delete '/jobs/:id/delete', to: 'jobs#delete', as: 'delete_job'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @jobs = Job.all
  end
  
  def show
    @job = Job.find(params[:id])
    if @job.nil?
      head :not_found
    end
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(
      title: params[:job][:title],
      description: params[:job][:description],
      company: params[:job][:company]
    )
    if @job.save
      redirect_to jobs_path
    else
      render :new, :bad_request
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    # find that job that we want to update
    @job = Job.find(params[:id])
    # update the job
    if @job.update(
      title: params[:job][:title],
      description: params[:job][:description],
      company: params[:job][:company]
    )
    # redirect if job is successfully update
      redirect_to job_path(@job.id)
    else
      # if not stay in the edit form
      render :edit, :bad_request
    end
  end

  def delete
    @job = Job.find(params[:id])
    if @job.destroy
      redirect_to jobs_path
    end 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/edit.html.erb
<h1>Edit new job</h1>
<%= form_with model: @job, class: 'book-form' do |f| %>
  <p> Please provide the following information</p>
  <div>
  <%= f.label :title%>
  <%= f.text_field :title%>
  </div>
  <br>
  <div>
  <%= f.label :description%>
  <%= f.text_area :description%>
  </div>
  <br>
  <div>
  <%= f.label :company%>
  <%= f.text_field :company%>
  </div>
  <br>
  <%= f.submit "edit a job", class: 'job-button'%>
<% end %>

app/views/jobs/index.html.erb
<h1>Jobs</h1>
<% @jobs.each do |job| %>
  <div class='job'>
  <strong> <%= link_to job.title, job_path(job.id) %></strong>
  <%= job.description %>
  <%= link_to 'Edit', edit_job_path(job.id)%>
  <%= link_to 'Delete', delete_job_path(job.id), method: :delete, data: { confirm: 'are you sure?'} %>
  </div>
<% end%>
  <p>
  <%= link_to 'Add a new job', jobs_new_path%>
  </p>

app/views/jobs/new.html.erb
<h1>Create new job</h1>
<%= form_with model: @job, class: 'book-form' do |f| %>
  <p> Please provide the following information</p>
  <div>
  <%= f.label :title%>
  <%= f.text_field :title%>
  </div>
  <br>
  <div>
  <%= f.label :description%>
  <%= f.text_area :description%>
  </div>
  <br>
  <div>
  <%= f.label :company%>
  <%= f.text_field :company%>
  </div>
  <br>
  <%= f.submit "add a job", class: 'job-button'%>
<% end %>

app/views/jobs/show.html.erb
<h2>Job Details<h2>
<div>
  <strong><%= @job.title %></strong>
  <p><%= @job.description %></p>
  <%= link_to 'Edit job', edit_job_path(@job.id) %>
  <%= link_to 'Delete job', delete_job_path(@job.id), method: :delete, data: {confirm: 'are you sure?'} %>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>